# Author: Mofiqul Islam <mofi0islam@gmail.com>

"attribute" = "orange_4"

"type" = "teal_2"
"type.builtin" = "teal_2"

"constructor" = "blue_2"

"constant" = "violet_2"
"constant.builtin" = { fg = "violet_2", modifiers = ["bold"] }
"constant.character" = "teal_3"
"constant.numeric" = { fg = "teal_3", modifiers = ["bold"] }
"constant.character.escape" = "violet_2"

"string" = "teal_2"
"string.regexp" = "purple_2"
"string.special" = "blue_2"

"comment" = "dark_2"

"variable" = "light_4"
"variable.parameter" = "orange_2"
"variable.builtin" = "orange_2"
"variable.other" = "teal_2"
"variable.other.member" = "teal_2"

"label" = "purple_2"

"punctuation" = "light_4"
"punctuation.delimiter" = "light_4"
"punctuation.bracket" = "light_4"
"punctuation.special" = "red_3"

"keyword" = { fg = "orange_2", modifiers = ["bold"] }
"keyword.control" = { fg = "orange_2", modifiers = ["bold"] }
"keyword.operator" = "purple_2"
"keyword.directive" = { fg = "orange_2", modifiers = ["bold"] }
"keyword.function" = "orange_2"
"keyword.storage" = { fg = "orange_2", modifiers = ["bold"] }

"operator" = "purple_2"

"function" = "blue_2"
"function.builtin" = "blue_2"
"function.macro" = { fg = "blue_2", modifiers = ["bold"] }
"function.special" = { fg = "blue_2", modifiers = ["bold"] }

"tag" = "teal_2"

"namespace" = "orange_2"

"markup" = "light_4"
"markup.heading" = { fg = "teal_2", modifiers = ["bold"] }
"markup.list" = { fg = "orange_2", modifiers = ["bold"] }
"markup.bold" = { fg = "light_4", modifiers = ["bold"] }
"markup.italic" = { fg = "light_4", modifiers = ["italic"] }
"markup.link" = { fg = "blue_3", modifiers = ["underlined"] }
"markup.quote" = { fg = "light_3", modifiers = ["italic"] }
"diff.plus" = "teal_3"
"diff.minus" = "red_1"
"diff.delta" = "orange_3"
"diff.delta.moved" = "orange_2"

"ui.background" = { fg = "light_4", bg = "libadwaita_dark" }
"ui.background.separator" = { fg = "split_and_borders", bg = "libadwaita_dark" }
"ui.selection" = { bg = "scale.blue.8" }
"ui.selection.primary" = { bg = "#2f426b" }
"ui.cursor.match" = { fg = "attention.fg", modifiers = [
  "bold",
], underline = { style = "line" } }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "#13171D" }

"ui.menu" = { fg = "fg.default", bg = "canvas.overlay" }
"ui.menu.selected" = { bg = "scale.gray.4" }
"ui.menu.scroll" = { fg = "scale.gray.5", bg = "canvas.overlay" }
"ui.linenr" = "dark_2"
"ui.linenr.selected" = { fg = "light_7", bg = "#13171D", modifiers = ["bold"] }
"ui.statusline" = { fg = "light_4", bg = "canvas.subtle" }
"ui.statusline.inactive" = { fg = "light_4", bg = "libadwaita_dark_alt" }
"ui.statusline.insert" = { fg = "light_4", bg = "teal_4" }
"ui.statusline.select" = { fg = "light_4", bg = "blue_4" }
"ui.popup" = { bg = "libadwaita_popup" }
"ui.window" = "split_and_borders"
"ui.help" = { bg = "libadwaita_dark_alt" }
"ui.text" = "light_4"
"ui.virtual" = "dark_1"
"ui.virtual.ruler" = { bg = "libadwaita_popup" }

"warning" = "yellow_2"
"error" = "red_4"
"info" = "purple_2"
"hint" = "blue_2"

"diagnostic.hint" = { fg = "blue_2", modifiers = ["dim"] }
"diagnostic.info" = { fg = "purple_2", modifiers = ["dim"] }
"diagnostic.error" = { fg = "red_4", modifiers = ["underlined"] }
"diagnostic.warning" = { fg = "yellow_2", modifiers = ["underlined"] }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

"ui.bufferline" = { fg = "dark_2", bg = "libadwaita_dark" }
"ui.bufferline.active" = { fg = "light_4", bg = "libadwaita_dark_alt" }

[palette]
blue_1 = "#99C1F1"
blue_2 = "#62A0EA"
blue_3 = "#3584E4"
blue_4 = "#1C71D8"
blue_5 = "#1A5FB4"
blue_6 = "#1B497E"
blue_7 = "#193D66"
brown_1 = "#CDAB8F"
brown_2 = "#B5835A"
brown_3 = "#986A44"
brown_4 = "#865E3C"
brown_5 = "#63452C"
chameleon_3 = "#4E9A06"
dark_1 = "#77767B"
dark_2 = "#5E5C64"
dark_3 = "#504E55"
dark_4 = "#3D3846"
dark_5 = "#241F31"
dark_6 = "#000000"
dark_7 = "#1c1c1c"
green_1 = "#8FF0A4"
green_2 = "#57E389"
green_3 = "#33D17A"
green_4 = "#2EC27E"
green_5 = "#26A269"
green_6 = "#1F7F56"
green_7 = "#1C6849"
# libadwaita_dark = "#1D1D1D"
libadwaita_dark = "#050505"
libadwaita_dark_alt = "#161b22"
libadwaita_popup = "#171b22"
light_1 = "#FFFFFF"
light_2 = "#FCFCFC"
light_3 = "#F6F5F4"
light_4 = "#DEDDDA"
light_5 = "#C0BFBC"
light_6 = "#B0AFAC"
light_7 = "#9A9996"
orange_1 = "#FFBE6F"
orange_2 = "#FFA348"
orange_3 = "#FF7800"
orange_4 = "#E66100"
orange_5 = "#C64600"
purple_1 = "#DC8ADD"
purple_2 = "#C061CB"
purple_3 = "#9141AC"
purple_4 = "#813D9C"
purple_5 = "#613583"
red_1 = "#F66151"
red_2 = "#ED3360"
red_3 = "#EC2F70"
red_4 = "#F74D73"
red_5 = "#EC4878"
teal_1 = "#93DDC2"
teal_2 = "#5BC8AF"
teal_3 = "#33B2A4"
teal_4 = "#26A1A2"
teal_5 = "#218787"
violet_2 = "#7D8AC7"
violet_3 = "#6362C8"
violet_4 = "#4E57BA"
yellow_1 = "#F9F06B"
yellow_2 = "#F8E45C"
yellow_3 = "#F6D32D"
yellow_4 = "#F5C211"
yellow_5 = "#E5A50A"
yellow_6 = "#D38B09"
split_and_borders = "#4F4F4F"
"accent.emphasis" = "#1f6feb"
"accent.fg" = "#58a6ff"
"accent.muted" = "#388bfd66"
"accent.subtle" = "#388bfd26"
"attention.emphasis" = "#9e6a03"
"attention.fg" = "#d29922"
"attention.muted" = "#bb800966"
"attention.subtle" = "#bb800926"
"border.default" = "#30363d"
"border.muted" = "#21262d"
"border.subtle" = "#f0f6fc1a"
"canvas.default" = "#0d1117"
"canvas.inset" = "#010409"
"canvas.overlay" = "#161b22"
"canvas.subtle" = "#161b22"
"closed.emphasis" = "#da3633"
"closed.fg" = "#f85149"
"closed.muted" = "#f8514966"
"closed.subtle" = "#f8514926"
"danger.emphasis" = "#da3633"
"danger.fg" = "#f85149"
"danger.muted" = "#f8514966"
"danger.subtle" = "#f8514926"
"done.emphasis" = "#8957e5"
"done.fg" = "#a371f7"
"done.muted" = "#a371f766"
"done.subtle" = "#a371f726"
"fg.default" = "#c9d1d9"
"fg.muted" = "#8b949e"
"fg.onEmphasis" = "#ffffff"
"fg.subtle" = "#6e7681"
"neutral.emphasis" = "#6e7681"
"neutral.emphasisPlus" = "#6e7681"
"neutral.muted" = "#6e768166"
"neutral.subtle" = "#6e76811a"
"open.emphasis" = "#238636"
"open.fg" = "#3fb950"
"open.muted" = "#2ea04366"
"open.subtle" = "#2ea04326"
"scale.black" = "#010409"
"scale.blue.0" = "#cae8ff"
"scale.blue.1" = "#a5d6ff"
"scale.blue.2" = "#79c0ff"
"scale.blue.3" = "#58a6ff"
"scale.blue.4" = "#388bfd"
"scale.blue.5" = "#1f6feb"
"scale.blue.6" = "#1158c7"
"scale.blue.7" = "#0d419d"
"scale.blue.8" = "#0c2d6b"
"scale.blue.9" = "#051d4d"
"scale.coral.0" = "#ffddd2"
"scale.coral.1" = "#ffc2b2"
"scale.coral.2" = "#ffa28b"
"scale.coral.3" = "#f78166"
"scale.coral.4" = "#ea6045"
"scale.coral.5" = "#cf462d"
"scale.coral.6" = "#ac3220"
"scale.coral.7" = "#872012"
"scale.coral.8" = "#640d04"
"scale.coral.9" = "#460701"
"scale.gray.0" = "#f0f6fc"
"scale.gray.1" = "#c9d1d9"
"scale.gray.2" = "#b1bac4"
"scale.gray.3" = "#8b949e"
"scale.gray.4" = "#6e7681"
"scale.gray.5" = "#484f58"
"scale.gray.6" = "#30363d"
"scale.gray.7" = "#21262d"
"scale.gray.8" = "#161b22"
"scale.gray.9" = "#0d1117"
"scale.green.0" = "#aff5b4"
"scale.green.1" = "#7ee787"
"scale.green.2" = "#56d364"
"scale.green.3" = "#3fb950"
"scale.green.4" = "#2ea043"
"scale.green.5" = "#238636"
"scale.green.6" = "#196c2e"
"scale.green.7" = "#0f5323"
"scale.green.8" = "#033a16"
"scale.green.9" = "#04260f"
"scale.orange.0" = "#ffdfb6"
"scale.orange.1" = "#ffc680"
"scale.orange.2" = "#ffa657"
"scale.orange.3" = "#f0883e"
"scale.orange.4" = "#db6d28"
"scale.orange.5" = "#bd561d"
"scale.orange.6" = "#9b4215"
"scale.orange.7" = "#762d0a"
"scale.orange.8" = "#5a1e02"
"scale.orange.9" = "#3d1300"
"scale.pink.0" = "#ffdaec"
"scale.pink.1" = "#ffbedd"
"scale.pink.2" = "#ff9bce"
"scale.pink.3" = "#f778ba"
"scale.pink.4" = "#db61a2"
"scale.pink.5" = "#bf4b8a"
"scale.pink.6" = "#9e3670"
"scale.pink.7" = "#7d2457"
"scale.pink.8" = "#5e103e"
"scale.pink.9" = "#42062a"
"scale.purple.0" = "#eddeff"
"scale.purple.1" = "#e2c5ff"
"scale.purple.2" = "#d2a8ff"
"scale.purple.3" = "#bc8cff"
"scale.purple.4" = "#a371f7"
"scale.purple.5" = "#8957e5"
"scale.purple.6" = "#6e40c9"
"scale.purple.7" = "#553098"
"scale.purple.8" = "#3c1e70"
"scale.purple.9" = "#271052"
"scale.red.0" = "#ffdcd7"
"scale.red.1" = "#ffc1ba"
"scale.red.2" = "#ffa198"
"scale.red.3" = "#ff7b72"
"scale.red.4" = "#f85149"
"scale.red.5" = "#da3633"
"scale.red.6" = "#b62324"
"scale.red.7" = "#8e1519"
"scale.red.8" = "#67060c"
"scale.red.9" = "#490202"
"scale.white" = "#ffffff"
"scale.yellow.0" = "#f8e3a1"
"scale.yellow.1" = "#f2cc60"
"scale.yellow.2" = "#e3b341"
"scale.yellow.3" = "#d29922"
"scale.yellow.4" = "#bb8009"
"scale.yellow.5" = "#9e6a03"
"scale.yellow.6" = "#845306"
"scale.yellow.7" = "#693e00"
"scale.yellow.8" = "#4b2900"
"scale.yellow.9" = "#341a00"
"severe.emphasis" = "#bd561d"
"severe.fg" = "#db6d28"
"severe.muted" = "#db6d2866"
"severe.subtle" = "#db6d2826"
"sponsors.emphasis" = "#bf4b8a"
"sponsors.fg" = "#db61a2"
"sponsors.muted" = "#db61a266"
"sponsors.subtle" = "#db61a226"
"success.emphasis" = "#238636"
"success.fg" = "#3fb950"
"success.muted" = "#2ea04366"
"success.subtle" = "#2ea04326"
