attribute = "#f1c67a"
keyword = "#bf8ed8"
"keyword.directive" = "lilac" # -- preprocessor comments (#if in C)
namespace = "#f19b99"
punctuation = "#505050"
"punctuation.delimiter" = "#505050"
operator = "#505050"
special = "honey"
"variable.other.member" = "#f1c67a"
variable = "#bbbbbb"
# variable = "almond" # TODO: metavariables only
# "variable.parameter" = { fg = "lavender", modifiers = ["underlined"] }
"variable.parameter" = { fg = "#DBDBDB" }
"variable.builtin" = "mint"
type = { fg = "#A6D279", modifiers = ["bold"] }
"type.builtin" = { fg = "#A6D279", modifiers = ["bold"] }
constructor = "#f19b99"
function = "#6295E3"
"function.macro" = "lilac"
"function.builtin" = "#f1c67a"
tag = "#f19b99"
comment = "#808080"
constant = "#7f89c3"
"constant.builtin" = "#7f89c3"
string = "#9fbd7f"
"constant.numeric" = "chamois"
"constant.character.escape" = "honey"
# used for lifetimes
label = "honey"

"markup.heading" = "#b1b9c3"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "#385085", modifiers = ["underlined"] }
"markup.link.text" = "almon"
"markup.raw" = "almond"

"diff.plus" = "#35bf86"
"diff.minus" = "#f22c86"
"diff.delta" = "#8360EE"

# TODO: diferentiate doc comment
# concat (ERROR) @error.syntax and "MISSING ;" selectors for errors

"ui.background" = { bg = "midnight", fg = "#2f3137"}
"ui.background.separator" = { fg = "comet" }
"ui.linenr" = { fg = "#5e5c64" }
"ui.linenr.selected" = { fg = "#9a9996", modifiers = ["bold"] }
"ui.statusline" = { fg = "#DEDDDA", bg = "revolver" }
"ui.statusline.inactive" = { fg = "#5d5c63", bg = "revolver" }
"ui.bufferline" = { fg = "#5d5d63", bg = "midnight" }
"ui.bufferline.active" = { fg = "#dedddb", bg = "revolver" }
"ui.popup" = { bg = "#0B0D11", fg = "#61687A" }
"ui.window" = { fg = "bossanova" }
"ui.help" = { bg = "#463380", fg = "#0A0923" }

"ui.text" = { fg = "#A7A7A7" }
"ui.text.focus" = { fg = "white" }
"ui.text.inactive" = "sirocco"
"ui.virtual" = { fg = "comet" }

"ui.virtual.indent-guide" = { fg = "comet" }

"ui.selection" = { bg = "#0c2d6b" }
"ui.selection.primary" = { bg = "#2f426b" }
# TODO: namespace ui.cursor as ui.selection.cursor?
"ui.cursor.select" = { bg = "delta" }
"ui.cursor.insert" = { bg = "white" }
"ui.cursor.match" = { fg = "#212121", bg = "#6C6999" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "bossanova" }
"ui.highlight" = { bg = "bossanova" }
"ui.highlight.frameline" = { bg = "#634450" }
"ui.debug" = { fg = "#634450" }
"ui.debug.breakpoint" = { fg = "apricot" }
"ui.menu" = { fg = "#DEDDDA", bg = "#0B0D11" }
"ui.menu.selected" = { fg = "revolver", bg = "#CBCAC7" }
"ui.menu.scroll" = { fg = "#9a9996", bg = "#5e5c64" }

"diagnostic.hint" = { fg = "#5e84be", modifiers = ["dim"] }
"diagnostic.info" = { fg = "delta", modifiers = ["dim"] }
"diagnostic.warning" = { fg = "#f4e573", modifiers = ["underlined"] }
"diagnostic.error" = { fg = "#FF6588", modifiers = ["underlined", "dim"] }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

warning = "#f4e573"
error = "#FF6588"
info = "delta"
hint = "#709ee4"

[palette]
white = "#ffffff"
lilac = "#dbbfef"
lavender = "#8E89DF"
comet = "#30333a"
bossanova = "#14171d"
midnight = "#050505"
revolver = "#171b22"

silver = "#cccccc"
sirocco = "#697C81"
mint = "#9ff28f"
almond = "#F0BB9A"
chamois = "#E8DCA0"
honey = "#efba5d"

apricot = "#f47868"
lightning = "#ffcd1c"
delta = "#6F44F0"

