theme = "alexandria"

[editor.lsp]
display-messages = true
# display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
bufferline = "multiple"
true-color = true
undercurl = true
idle-timeout = 0
cursorline = true
completion-trigger-len = 1

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 500

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

# [editor.whitespace.render]
# space = "all"
# tab = "all"
# newline = "none"

[editor.whitespace.characters]
space = "→"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "→" # Tabs will look like "→···" (depending on tab width)

[editor.file-picker]
hidden = false

[keys.normal]
# "ret" = ["move_line_down", "goto_first_nonwhitespace"] # Maps the enter key to move to start of next line
a = ["insert_mode", "move_char_right", "collapse_selection"]
Y = ":yank-diagnostic"
"$" = "goto_line_end"
# "A-/" = "toggle_comments"
G = "goto_file_end"
y = ":clipboard-yank"
q = ":clipboard-yank"
p = ":clipboard-paste-before"
"§" = "select_textobject_inner"
"{" = ":buffer-previous"
"}" = ":buffer-next"
# "A-left" = "move_prev_word_start"
# "A-right" = ["move_next_word_end", "move_char_right"]
"A-left" = "goto_line_start"
"A-right" = "goto_line_end"
"A-f" = "goto_line_end"
"A-b" = ["goto_line_start", "move_next_word_end", "move_prev_word_start", "move_char_right", "move_char_left", "collapse_selection"]
# "A-f" = ["move_next_word_end", "move_char_right" , "collapse_selection"]
# "A-b" = ["move_prev_word_start", "collapse_selection"]
"A-up" = ["expand_selection"]
"A-down" = ["shrink_selection"]
w = ["move_prev_word_start", "collapse_selection"]
f = ["move_next_word_start", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]
"minus" = ["goto_line_start", "move_next_word_start", "move_char_right", "collapse_selection"]
"=" = "goto_line_end"
"0" = "goto_line_start"
"C-n" = ["move_char_left", "collapse_selection"]
"C-o" = ["move_char_right", "collapse_selection"]
"C-e" = ["move_line_down", "collapse_selection"]
"C-i" = ["move_line_up", "collapse_selection"]
"C-w" = ["move_prev_word_start", "collapse_selection"]
"C-f" = ["move_next_word_start", "collapse_selection"]
"A-'" = ["scroll_up", "scroll_up", "scroll_up", "scroll_up"]
"A-/" = ["scroll_down", "scroll_down", "scroll_down", "scroll_down"]
"S-up" = ["half_page_up"]
"S-down" = ["half_page_down"]
# t = ["insert_mode", "insert_newline"]
t = "goto_word"
l = "jump_backward"
"S-l" = "jump_forward"
"S-left" = "jump_view_left"
"S-right" = "jump_view_right"
"\"" = "jump_view_up"
"?" = "jump_view_down"
"S-v" = "vsplit"
"S-h" = "hsplit"
W = "wclose"

[keys.insert]
"S-ret" = ["open_above", "move_line_down"]
"ret" = ["insert_newline", "move_line_up", "insert_at_line_end", "move_line_down"]
"A-i" = "insert_at_line_end"
"§" = "completion"
"A-{" = ":buffer-previous"
"A-}" = ":buffer-next"
"up" = "move_line_up"
"down" = "move_line_down"
"left" = "move_char_left"
"right" = "move_char_right"
"A-left" = "move_prev_word_start"
"A-right" = ["move_next_word_end", "move_char_right"]
"A-f" = ["move_next_word_end", "move_char_right", "collapse_selection"]
"A-b" = ["move_prev_word_start", "collapse_selection"]
# "esc" = ["normal_mode", ":w"]
"A-'" = ["scroll_up", "scroll_up", "scroll_up", "scroll_up"]
"A-/" = ["scroll_down", "scroll_down", "scroll_down", "scroll_down"]
"S-up" = ["half_page_up"]
"S-down" = ["half_page_down"]
"A-minus" = ["goto_line_start", "move_next_word_start", "move_char_right", "collapse_selection"]
"A-=" = "goto_line_end"
"A-0" = "goto_line_start"

[keys.normal.space]
q = ":write-quit"
c = ":buffer-close"
f = "file_picker_in_current_directory"
F = "file_picker"
w = [":format", ":w"]
"S-[" = ["surround_delete"]
x = ["yank_to_clipboard", "delete_selection"]
l = ":lsp-restart"
"[" = "surround_delete"
t = "hover"
H = ":config-reload"

[keys.select]
q = ":clipboard-yank"
t = "extend_to_word"
y = [":clipboard-yank", "normal_mode"]
Y = ":yank-diagnostic"
"0" = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
n = "move_char_left"
o = "move_char_right"
e = "move_line_down"
i = "move_line_up"
w = "extend_prev_word_start"
f = "extend_next_word_start"
"A-'" = ["scroll_up", "scroll_up", "scroll_up", "scroll_up"]
"A-/" = ["scroll_down", "scroll_down", "scroll_down", "scroll_down"]
"S-up" = "half_page_up"
"S-down" = ["half_page_down"]

[keys.normal.'space'.'space']
# Extensions using custom script
# Interactive search in current working directory
s = ":pipe-to helix-ext search --current"
# Interactive search in current working directory (include path name in the search)
S = ":pipe-to helix-ext search --current-inc-path"
# Interactive search in current git directory
w = ":pipe-to helix-ext search --workspace"
# Interactive search in current git directory (include path name in the search)
W = ":pipe-to helix-ext search --workspace-inc-path"
# Interactive search in current buffer
b = ":pipe-to helix-ext search --buffer"
# Git status
m = ":pipe-to helix-ext git --status"
# Git blame
B = ":pipe-to helix-ext git --blame"
# Git browse github repo using default browser
O = ":pipe-to helix-ext git --browse"
