[language-server.gpt]
command = "bun"
args = ["run", "/usr/local/bin/helix-gpt"]

[language-server.copilot]
command = "copilot"
args = ["--stdio"]

[language-server.uwu_colors]
command = "uwu_colors"

[language-server.typescript]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.typescript.config]
typescript.tsserver.experimental.enableProjectDiagnostics = true

[language-server.tsx.config]
typescript.tsserver.experimental.enableProjectDiagnostics = true

[language-server.tsx]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]

[language-server.efm]
command = "efm-langserver"

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.biome]
command = "biome"
args = ["lsp-proxy", "--config-path", "biome.json"]

[language-server.vscode-json-language-server.config]
json = { validate = { enable = true }, format = { enable = true } }
provideFormatter = true

[language-server.vscode-css-language-server.config]
css = { validate = { enable = true } }
scss = { validate = { enable = true } }
less = { validate = { enable = true } }
provideFormatter = true

[language-server.eslint.config]
validate = "on"
experimental = { useFlatConfig = false }
rulesCustomizations = []
run = "onType"
problems = { shortenToSingleLine = false }
nodePath = ""

[language-server.eslint.config.codeAction]
[language-server.eslint.config.codeAction.disableRuleComment]
enable = true
location = "separateLine"

[language-server.eslint.config.codeAction.showDocumentation]
enable = true

[language-server.eslint.config.codeActionOnSave]
enable = true
mode = "fixAll"

[language-server.eslint.config.workingDirectory]
mode = "location"

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
file-types = ["ts"]
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  { name = "copilot" },
  { name = "eslint", except-features = ["format"] },
  { name = "emmet-ls" },
  { name = "uwu_colors" }
]

[[language]]
name = "tsx"
formatter = { command = "prettier", args = ["--stdin-filepath", "file.tsx"] }
file-types = ["tsx"]
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  { name = "copilot" },
  { name = "eslint", except-features = ["format"] },
  { name = "emmet-ls" },
  { name = "uwu_colors" }
]

[[language]]
name = "haskell"
file-types = ["hs"]
language-servers = [
  { name = "haskell-language-server" },
  { name = "copilot" },
  { name = "uwu_colors" }
]

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }
language-servers = ["uwu_colors"]

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml"] }
language-servers = ["yaml-language-server", "copilot", "uwu_colors"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "emmet-ls", "uwu_colors"]
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "css"
language-servers = [
  "vscode-css-language-server",
  "emmet-ls",
  "copilot",
  "uwu_colors"
]
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "cpp"
language-servers = ["clangd", "copilot", "uwu_colors"]

[[language]]
name = "svelte"
language-servers = ["svelteserver", "eslint", "uwu_colors"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "copilot", "uwu_colors"]

[[language]]
name = "toml"
language-servers = ["taplo", "copilot", "uwu_colors"]

[[language]]
name = "go"
language-servers = ["gopls", "copilot", "uwu_colors"]
